ejemplo PALABRACLAVE hoy5

diff --git a/.github/workflows/palabraclave.yml b/.github/workflows/palabraclave.yml
--- a/.github/workflows/palabraclave.yml
+++ b/.github/workflows/palabraclave.yml
@@ -49,7 +49,9 @@ jobs:
 
     - name: Validar resultado con errores
       if: ${{ failure() }}
-        exit 1
+      run: |
+          echo "Error"
+          exit 1
 
     - name: Validar resultado sin errores
       if: ${{ success() }}
